# Generated by Django 6.0 on 2026-01-05 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_adm', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('senha', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('data_producao', models.DateField(blank=True, null=True)),
                ('status_logistica', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id_produtor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'produtor',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('produtor', 'Produtor'), ('empresa', 'Empresa'), ('gestor', 'Gestor'), ('operador', 'Operador')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificacao',
            fields=[
                ('id_certificacao', models.AutoField(primary_key=True, serialize=False)),
                ('data_certificacao', models.DateField(blank=True, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comerciojusto.administrador')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comerciojusto.produto')),
            ],
            options={
                'db_table': 'certificacao',
            },
        ),
        migrations.CreateModel(
            name='AnuncioMarketplace',
            fields=[
                ('id_anuncio', models.AutoField(primary_key=True, serialize=False)),
                ('plataforma', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comerciojusto.produto')),
            ],
            options={
                'db_table': 'anuncio_marketplace',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='produtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comerciojusto.produtor'),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('arquivo', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comerciojusto.produtor')),
            ],
            options={
                'db_table': 'documento',
            },
        ),
    ]
